# Generated by Django 5.1.1 on 2024-10-15 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profileuser_gallery_alter_profileuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='gallery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.galleryuser', verbose_name='Галерея'),
        ),
    ]
