# Generated by Django 5.1.1 on 2024-10-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profileuser_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='Народження'),
        ),
    ]
