# Generated by Django 5.1.1 on 2024-10-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profileuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='photo',
            field=models.ImageField(blank=True, default='user_styles/User.png', upload_to='users_photo/', verbose_name='Основна світлина'),
        ),
    ]
