# Generated by Django 5.1.1 on 2024-10-16 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profileuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.galleryuser', verbose_name='Галерея'),
        ),
    ]
