# Generated by Django 5.1.1 on 2024-10-16 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_galleryuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='gallery',
        ),
    ]
