# Generated by Django 5.1.1 on 2024-10-16 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_galleryimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GalleryImage',
            new_name='ImagesUser',
        ),
        migrations.RenameField(
            model_name='imagesuser',
            old_name='image',
            new_name='images',
        ),
        migrations.RemoveField(
            model_name='galleryuser',
            name='gallery',
        ),
    ]
