# Generated by Django 5.1.1 on 2024-10-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_galleryimage_imagesuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesuser',
            name='video',
            field=models.FileField(blank=True, upload_to='users_video/gallery/', verbose_name='Відео'),
        ),
    ]
