# Generated by Django 5.1.1 on 2024-10-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_imagesuser_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesuser',
            name='images',
            field=models.ImageField(blank=True, upload_to='users_photo/gallery/', verbose_name='Зображення'),
        ),
    ]
