# Generated by Django 5.1.1 on 2024-11-06 19:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_galleryuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesuser',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата'),
            preserve_default=False,
        ),
    ]
