# Generated by Django 5.1.1 on 2024-11-07 20:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_imagesuser_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryuser',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galleryuser',
            name='images',
            field=models.ImageField(blank=True, upload_to='users_photo/gallery/', verbose_name='Зображення'),
        ),
        migrations.AddField(
            model_name='galleryuser',
            name='videos',
            field=models.FileField(blank=True, upload_to='users_video/gallery/', verbose_name='Відео'),
        ),
        migrations.AlterField(
            model_name='galleryuser',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Основний User'),
        ),
        migrations.DeleteModel(
            name='ImagesUser',
        ),
    ]
