# Generated by Django 5.1.1 on 2024-11-08 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_galleryuser_date_galleryuser_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryuser',
            name='date',
        ),
        migrations.RemoveField(
            model_name='galleryuser',
            name='images',
        ),
        migrations.RemoveField(
            model_name='galleryuser',
            name='videos',
        ),
        migrations.CreateModel(
            name='ImagesUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='users_photo/gallery/', verbose_name='Зображення')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('gallery', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.galleryuser', verbose_name='Основний User')),
            ],
        ),
        migrations.CreateModel(
            name='VideosUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videos', models.FileField(blank=True, upload_to='users_video/gallery/', verbose_name='Відео')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('gallery', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.galleryuser', verbose_name='Основний User')),
            ],
        ),
    ]
