# Generated by Django 5.1.1 on 2024-10-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Назва')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='Фотографія')),
                ('price', models.IntegerField(blank=True, verbose_name='Ціна')),
            ],
            options={
                'verbose_name': 'Назва',
                'verbose_name_plural': 'Назви',
            },
        ),
    ]
