# Generated by Django 5.1.1 on 2024-10-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_clubmodel_coutrymodel_alter_productsmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmodel',
            name='team',
            field=models.CharField(max_length=30, verbose_name='Клуб'),
        ),
        migrations.AlterField(
            model_name='coutrymodel',
            name='country',
            field=models.CharField(max_length=30, verbose_name='Країна'),
        ),
    ]
