# Generated by Django 5.1.1 on 2024-10-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_clubmodel_team_alter_coutrymodel_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Назва бренду')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренди',
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Назва категорії')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Країна походження')),
            ],
            options={
                'verbose_name': 'Країна',
                'verbose_name_plural': 'Країни',
            },
        ),
        migrations.RemoveField(
            model_name='productsmodel',
            name='team',
        ),
        migrations.RemoveField(
            model_name='productsmodel',
            name='country',
        ),
        migrations.RemoveField(
            model_name='productsmodel',
            name='position',
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Назва товару'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='price',
            field=models.IntegerField(verbose_name='Ціна'),
        ),
        migrations.DeleteModel(
            name='ClubModel',
        ),
        migrations.DeleteModel(
            name='CoutryModel',
        ),
    ]
