# Generated by Django 5.1.1 on 2024-10-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_brandmodel_categorymodel_countrymodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Ціна'),
        ),
    ]
