# Generated by Django 5.1.1 on 2024-10-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_productsmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ціна'),
        ),
    ]
