# Generated by Django 5.1.1 on 2024-10-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_productsmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='products/', verbose_name='Фото'),
        ),
    ]
