# Generated by Django 5.1.1 on 2024-10-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_productsmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='price',
            field=models.FloatField(default=0, verbose_name='Ціна'),
        ),
    ]
