# Generated by Django 5.1.1 on 2024-10-03 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_productsmodel_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=5, verbose_name='Розміри')),
            ],
            options={
                'verbose_name': 'Розмір',
                'verbose_name_plural': 'Розміри',
            },
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='brand',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='shop.brandmodel', verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='shop.categorymodel', verbose_name='Категорія'),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='shop.countrymodel', verbose_name='Країна'),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата публкації'),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='size',
            field=models.ManyToManyField(to='shop.sizemodel', verbose_name='Розміри'),
        ),
    ]
