# Generated by Django 5.1.1 on 2024-10-03 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_sizemodel_productsmodel_brand_productsmodel_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SexModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=5, verbose_name='Стать')),
            ],
            options={
                'verbose_name': 'Стать',
                'verbose_name_plural': 'Стать',
            },
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='sex',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='shop.sexmodel', verbose_name='Стать'),
        ),
    ]
