# Generated by Django 5.1.1 on 2024-10-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_sexmodel_productsmodel_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/', verbose_name='Фото'),
        ),
    ]
