# Generated by Django 5.1.1 on 2024-10-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_productsmodel_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='about',
            field=models.TextField(blank=True, max_length=300, verbose_name='Інформація'),
        ),
    ]
