# Generated by Django 5.1.1 on 2024-10-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_productsmodel_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Ціна'),
        ),
    ]
