# Generated by Django 5.1.1 on 2024-10-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_productsmodel_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Імя')),
                ('achievement', models.CharField(max_length=300, verbose_name='Досягення')),
                ('experience', models.CharField(max_length=300, verbose_name='Досвід')),
                ('skills', models.CharField(max_length=300, verbose_name='Досвід')),
                ('image', models.ImageField(upload_to='products/admins/', verbose_name='Фото')),
                ('bio', models.TextField(verbose_name='Біографія')),
            ],
            options={
                'verbose_name': 'Імя',
                'verbose_name_plural': 'Імена',
            },
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name='Фото'),
        ),
    ]
