# Generated by Django 5.1.1 on 2024-10-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_administrationmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='video',
            field=models.FileField(blank=True, upload_to='products/video/', verbose_name='Відеоогляд'),
        ),
    ]
