# Generated by Django 5.1.1 on 2024-11-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_productsmodel_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrationmodel',
            name='achievement',
            field=models.CharField(blank=True, max_length=300, verbose_name='Досягення'),
        ),
        migrations.AlterField(
            model_name='administrationmodel',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Біографія'),
        ),
        migrations.AlterField(
            model_name='administrationmodel',
            name='experience',
            field=models.CharField(blank=True, max_length=300, verbose_name='Досвід'),
        ),
        migrations.AlterField(
            model_name='administrationmodel',
            name='skills',
            field=models.CharField(blank=True, max_length=300, verbose_name='Посада'),
        ),
    ]
