# Generated by Django 5.1.1 on 2024-10-11 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0015_alter_productsmodel_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва продукту')),
                ('address', models.CharField(max_length=50, verbose_name='Адреса')),
                ('phone', models.IntegerField(default=0, verbose_name='Телефон')),
                ('mail', models.EmailField(blank=True, max_length=254, verbose_name='Електронна пошта')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Кількість')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='Розмір')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.clientdata', verbose_name='Дані клієнта')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productsmodel', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
            },
        ),
    ]
