# Generated by Django 5.1.1 on 2024-10-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdata',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Коментар'),
        ),
    ]
