# Generated by Django 5.1.1 on 2024-10-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_clientdata_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Коментар'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
