# Generated by Django 5.1.1 on 2024-10-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_clientdata_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='order_number',
            field=models.PositiveIntegerField(default=1, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сума замовлення'),
        ),
    ]
